//! **`editor/classes.json`** — the class tree, its fields and its hooks.
//!
//! ⚠ **The palette says what a developer can *place*; this says what a developer can *inspect*.** They
//! are different questions and the palette cannot answer the second: it carries ops, not classes, so
//! nothing in it names a base, an ancestry, or a hook.
//!
//! # Which is why three of M17's panels had no data
//!
//! ⚠ **The inspector needs `exposed` and `mutable`**, the OVERRIDES list needs **every hook in the
//! ancestry**, and a default has to render **as prose**. All three facts live in `manifest/tier1.toml`
//! — the manifest even documents `hook = true` as *"what generates a schematic's OVERRIDES list"* — and
//! none of them reached the editor, because no artifact carried them.
//!
//! ▶ **Read, never asked for**, exactly like the palette. Regenerated by `cargo xtask generate`, and
//! `cargo xtask check` fails when it is stale — so the editor's idea of the type tree cannot drift from
//! the compiler's.

use cv_manifest::model::{Class, Manifest, Status};
use std::fmt::Write as _;

/// JSON-escape a string.
fn q(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Every ancestor of a class, nearest first, following `extends`.
///
/// ⚠ **Nearest first, because that is override order.** The OVERRIDES list shows the hook a developer
/// would be replacing, and the one that applies is the closest declaration — presenting the chain
/// root-first would put `/Core/Object` at the top of every panel and bury what matters.
fn ancestry<'a>(m: &'a Manifest, c: &'a Class) -> Vec<&'a Class> {
    let mut out = Vec::new();
    let mut cur = c;
    let mut guard = 0;
    while let Some(parent) = cur.extends.as_deref() {
        // The validator reports a cycle properly; this only has to not spin.
        guard += 1;
        if guard > 16 {
            break;
        }
        let Some(next) = m.get(parent) else { break };
        out.push(next);
        cur = next;
    }
    out
}

/// Emit the class artifact.
pub fn emit(m: &Manifest) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "{{");
    // JSON has no comments, so the banner is a field. First, so it survives a truncated read.
    let _ = writeln!(
        s,
        "  \"generated\": {},",
        q(&crate::banner("").replace('\n', " "))
    );
    let _ = writeln!(s, "  \"classes\": [");

    let stable: Vec<&Class> = m
        .classes
        .iter()
        .filter(|c| c.status == Status::Stable)
        .collect();
    for (i, c) in stable.iter().enumerate() {
        let comma = if i + 1 == stable.len() { "" } else { "," };
        let _ = writeln!(s, "    {{");
        let _ = writeln!(s, "      \"path\": {},", q(&c.path));
        let _ = writeln!(s, "      \"name\": {},", q(c.short_name()));
        let _ = writeln!(
            s,
            "      \"kind\": {},",
            q(&format!("{:?}", c.kind()).to_lowercase())
        );
        if let Some(e) = &c.extends {
            let _ = writeln!(s, "      \"extends\": {},", q(e));
        }
        let chain: Vec<String> = ancestry(m, c).iter().map(|a| q(&a.path)).collect();
        let _ = writeln!(s, "      \"ancestry\": [{}],", chain.join(", "));
        let _ = writeln!(s, "      \"doc\": {},", q(&c.doc));

        // --- fields -----------------------------------------------------------------------
        let fields: Vec<&_> = c
            .fields
            .iter()
            .filter(|f| f.status == Status::Stable)
            .collect();
        let _ = writeln!(s, "      \"fields\": [");
        for (j, f) in fields.iter().enumerate() {
            let fc = if j + 1 == fields.len() { "" } else { "," };
            let _ = write!(
                s,
                "        {{ \"name\": {}, \"type\": {}, \"exposed\": {}, \"mutable\": {}, \"api\": {}, \"doc\": {}",
                q(&f.name), q(&f.ty), f.exposed, f.mutable, f.api, q(&f.doc)
            );
            if let Some(d) = &f.default {
                let _ = write!(s, ", \"default\": {}", q(d));
            }
            let _ = writeln!(s, " }}{fc}");
        }
        let _ = writeln!(s, "      ],");

        // --- methods, and which of them are hooks ------------------------------------------
        let methods: Vec<&_> = c
            .methods
            .iter()
            .filter(|x| x.status == Status::Stable)
            .collect();
        let _ = writeln!(s, "      \"methods\": [");
        for (j, me) in methods.iter().enumerate() {
            let mc = if j + 1 == methods.len() { "" } else { "," };
            let _ =
                write!(
                s,
                "        {{ \"name\": {}, \"hook\": {}, \"api\": {}, \"returns\": {}, \"doc\": {}",
                q(&me.name), me.hook, me.api, q(&me.returns), q(&me.doc)
            );
            if let Some(d) = &me.default {
                let _ = write!(s, ", \"default\": {}", q(d));
            }
            let _ = writeln!(s, " }}{mc}");
        }
        // --- enum variants ------------------------------------------------------------------
        // ⚠ **A hole the Details panel found the way M17 found three others: by needing the data.**
        // Fifteen enum classes reached the artifact with empty `fields` and nothing else, while the
        // manifest declares six variants for `/Core/Face` alone. ▶ **A dropdown cannot be drawn
        // from a type name**, so the panel would have had to guess or degrade to a text box.
        if !c.values.is_empty() {
            // ⚠ An `EnumValue` carries no status of its own — the class's status covers it.
            let vals: Vec<&_> = c.values.iter().collect();
            let _ = writeln!(s, "      ],");
            let _ = writeln!(s, "      \"values\": [");
            for (j, v) in vals.iter().enumerate() {
                let vc = if j + 1 == vals.len() { "" } else { "," };
                let _ = writeln!(
                    s,
                    "        {{ \"name\": {}, \"doc\": {} }}{vc}",
                    q(&v.name),
                    q(&v.doc)
                );
            }
            let _ = writeln!(s, "      ]");
        } else {
            let _ = writeln!(s, "      ]");
        }
        let _ = writeln!(s, "    }}{comma}");
    }

    let _ = writeln!(s, "  ]");
    let _ = writeln!(s, "}}");
    s
}
