import { describe, it, expect } from "vitest";
import { recordRng, recordTrig } from "./record.js";
import * as rng from "../rng.js";
import * as trig from "../trig.js";
import rngGolden from "./rng.golden.json";
import trigGolden from "./trig.golden.json";

/**
 * Hermetic parity check: the ported determinism math must reproduce the recorded
 * reference vectors byte-for-byte. If this fails, worlds generated by CycleVania
 * would diverge from the reference (and co-op clients would desync). Regenerate
 * ONLY via `node scripts/gen-golden.ts` after a deliberate reference change.
 */
// Compare through JSON serialization — the same canonical form the generator
// asserts parity in (which folds -0/+0 and matches the committed file exactly).
const canon = (x: unknown): string => JSON.stringify(x);

describe("golden parity", () => {
  it("rng reproduces the recorded reference vectors", () => {
    expect(canon(recordRng(rng))).toBe(canon(rngGolden));
  });

  it("trig reproduces the recorded reference vectors", () => {
    expect(canon(recordTrig(trig))).toBe(canon(trigGolden));
  });
});
