export type { ComposeContext } from "./context.js";
export { composeRoom, composeArena } from "./room-composer.js";
export type { RoomComposeParams, SocketRequest, ContentRequest, RoomShape } from "./room-composer.js";
export { composeArea } from "./area-composer.js";
export type { AreaComposeParams, PortalRequest } from "./area-composer.js";
export { corridorGeometry } from "./connector-composer.js";
export type { ConnectorGeom } from "./connector-composer.js";
export { composeReach } from "./reach-composer.js";
export type { ComposeReachOptions, ReachResult } from "./reach-composer.js";
export { composeWorld, reachGadgets } from "./world-composer.js";
export type { ComposeWorldOptions, WorldResult } from "./world-composer.js";
