/**
 * **The node palette, and the type declarations beside it.**
 *
 * ⚠ **Read, never asked for.** Both `palette.json` and `index.d.ts` are build outputs of
 * `manifest/tier1.toml`, regenerated by `cargo xtask generate`. Nothing here computes a palette at
 * runtime, and nothing here may edit one: an editor that derived the node list would be a second
 * opinion about the API surface, and the two would drift the moment the manifest changed.
 *
 * ▶ **This is why `cargo xtask check` fails on a stale artifact.** The palette the editor shows and the
 * ops the compiler accepts come from one file, so *"the palette offers a node the compiler has never
 * heard of"* is a build failure rather than a bug report. That exact mismatch happened once, across
 * 348 nodes.
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const editorRoot = path.resolve(here, "..");
const repoRoot = path.resolve(editorRoot, "..");

/** One entry a developer can drop onto a schematic. */
export interface PaletteNode {
  /** The op the compiler dispatches on, e.g. `/Core/Object.is_a`. */
  op: string;
  /** Where it sits in the browser's tree. */
  category: string;
  /** The label shown on the node. */
  label: string;
  /** The developer-facing description. */
  doc?: string;
  /** Input pins, in order. */
  inputs?: { name: string; type: string }[];
  /** Output pins, in order. */
  outputs?: { name: string; type: string }[];
}

let cached: PaletteNode[] | undefined;

/**
 * Every node in the palette.
 *
 * ⚠ **Fails loudly when the file is missing**, rather than returning an empty palette. An editor that
 * silently offered nothing would look like a project with no content, which is a different problem and
 * sends whoever hit it to the wrong place.
 */
export function palette(): PaletteNode[] {
  if (cached) return cached;
  const at = path.join(editorRoot, "palette.json");
  let raw: string;
  try {
    raw = readFileSync(at, "utf8");
  } catch {
    throw new Error(
      `the node palette is missing at ${at} — run \`cargo xtask generate\` from the repository root`,
    );
  }
  const parsed = JSON.parse(raw) as PaletteNode[] | { nodes: PaletteNode[] };
  cached = Array.isArray(parsed) ? parsed : parsed.nodes;
  return cached;
}

/** The palette grouped by category, for the browser's tree. */
export function byCategory(): Map<string, PaletteNode[]> {
  const out = new Map<string, PaletteNode[]>();
  for (const node of palette()) {
    const list = out.get(node.category);
    if (list) list.push(node);
    else out.set(node.category, [node]);
  }
  return out;
}

/**
 * The generated TypeScript declarations, as text.
 *
 * ⚠ **The editor reads them; it does not typecheck against them at runtime.** They are here so an
 * inspector can show a member's real signature and doc rather than a guess — the same file a host
 * compiles against, so what the editor displays is what a host gets.
 */
export function declarations(): string {
  const at = path.join(repoRoot, "crates", "cv-bindings", "index.d.ts");
  try {
    return readFileSync(at, "utf8");
  } catch {
    throw new Error(
      `the API declarations are missing at ${at} — run \`cargo xtask generate\` from the repository root`,
    );
  }
}
